### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CyborG300** [neil-morrison44/pocket-sync#330] opened 2024-10-11 03:46 UTC
Cores: Mazamars312.NeoGeo
Invalid regular expression: invalid group specifier name
RegExp@[native code]
tp@tauri://localhost/assets/index-DDE29Y7S.js:51:143250
r@tauri://localhost/assets/index-DDE29Y7S.js:41:102784
$h@tauri://localhost/assets/index-DDE29Y7S.js:51:139659
O0@tauri://localhost/assets/index-C-0OVoc9.js:39:74634
SA@tauri://localhost/assets/index-C-0OVoc9.js:41:129663
vA@tauri://localhost/assets/index-C-0OVoc9.js:41:125395
cP@tauri://localhost/assets/index-C-0OVoc9.js:41:125323
vd@tauri://localhost/assets/index-C-0OVoc9.js:41:125175
__@tauri://localhost/assets/index-C-0OVoc9.js:41:121539
mA@tauri://localhost/assets/index-C-0OVoc9.js:41:120488
mA@[native code]
A@tauri://localhost/assets/index-C-0OVoc9.js:26:10721
Z@tauri://localhost/assets/index-C-0OVoc9.js:26:11083
**Describe the bug**
A clear and concise description of what the bug is. Ideally including the error message.
I just updated to the new version and I went to update my cores and now I can't click on any of them I keep getting that error above and now I can't use the app 
**To Reproduce**
Steps to reproduce the behaviour:

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**

**Screenshots**

**Logs**
Copy over the log from the folder that opens when you click the "Open Log Folder" button at the bottom of settings.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 11]

**Additional context**

**Comment by neil-morrison44** [comment] 2024-10-11 11:07
What OS / Version are you using?

**Comment by CyborG300** [comment] 2024-10-11 19:47
Mac

**Comment by neil-morrison44** [comment] 2024-10-13 03:35
This is a regression on the fix for https://github.com/neil-morrison44/pocket-sync/issues/313

I’ll get it pinned to the older version again for the next release, however it is worth reiterating that due to the nature of the framework I use I can only really guarantee support for the most recent 2 versions of macOS

**Comment by neil-morrison44** [comment] 2024-10-13 18:38
Should be fixed in v5.2.0 now

**Closed by neil-morrison44** 2024-10-13 18:38 UTC
Labels: bug
