### ISSUE TITLE
Can't Install New Cores

### ISSUE THREAD

**Issue by davisgiles** [neil-morrison44/pocket-sync#165] opened 2023-10-25 21:03 UTC
**Describe the bug**
When on the cores tab, I select the new core I would like to install and it loads the core page but when I click the 'install' button nothing responds. There is no error message but the button does nothing. The entire app functions well and I can use/view anything but cannot install new cores.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Cores tab
2. Click on any core
3. Click the 'install' button in the top right
4. No error message, but the button doesn't respond. 

If the error only appeared after installing a certain core or image pack say which one.

**Expected behaviour**
When I choose a core to install, it installed the core and all associated files. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MACOS 
 - Version: Sonoma 14.0

**Additional context**

**Comment by neil-morrison44** [comment] 2023-10-26 00:51
Very strange, never heard of that before.

One thing that _might_ make sense is if you somehow hit the GitHub free rate limit from your IP & it wasn’t able to download the zips from GitHub (not even 100% sure they count towards the rate limit).

The issue would fix itself once the limit reset though…

Was an issue in the past when people would run one of the update-everything updaters then switch to Pocket Sync having exhausted all the free requests for that hour - but we all changed to hit GitHub less and it’s not been an issue for a while.

**Comment by joelekstrom** [comment] 2023-10-29 05:26
I also had this problem the first time I ran the app - the install button simply did nothing. It started working after a while though, not sure why

**Comment by davisgiles** [comment] 2023-10-30 21:55
I had used the app before with no problem and then encountered the issue. But same as @joelekstrom after a few restarts it corrected itself. Can confirm the installs of new cores are working. Closing this issue.

**Comment by joelekstrom** [comment] 2023-10-31 21:25
I’d keep this open, seems like other people are seeing the same https://www.reddit.com/r/AnaloguePocket/comments/17irhrf/pocket_sync_cant_install_cores/

**Comment by neil-morrison44** [comment] 2023-11-01 01:11
Yeah, it’s definitely real - still no idea what the root cause would be & why it’d start happening so recently to a bit of the app that hasn’t changed in ages.

I’m dealing with some house stuff (specifically some upstairs neighbour went to sleep with a tap on stuff) so I can’t put as much time into it as I’d like

**Comment by neil-morrison44** [comment] 2023-11-02 02:30
If anyone finds their way to this issue having encountered it, hopefully with v3.9.3 you'll have got a more informative error message - if you could let me know what it said that'd be really helpful

**Comment by colemichaelwenger** [comment] 2023-11-25 00:08
I am on v3.10.1 on MacOS Ventura 13.3.1 and had the same issue. No error messages happened. A click just does nothing with no feedback. One restart fixed the issue, however. If you're logging out, let me know where to and I'll pull it for more info.

**Comment by neil-morrison44** [comment] 2023-12-05 00:17
Still not sure what would cause this, nor have I been able to manage to get it happening - someone one Reddit did report the _uninstall_ button was similarly unresponsive, which (if that's the same thing) suggests it's a UI issue.

Doesn't make sense that it'd go away by itself after a number of restarts though.

If you get this happening a screen recording would probably be useful - to see if the button is highlighting as it should etc

**Comment by ViktorEvil** [comment] 2023-12-06 14:42
the button highlights as you would expect but nothing else happens

**Comment by neil-morrison44** [comment] 2023-12-10 22:44
In v4.0.0 I've swapped the buttons around completely, hopefully fixing whatever this was - going to keep an eye on it and if it doesn't get reported with any post-v4.0.0 version I'll close this off

**Comment by arturomartin** [comment] 2023-12-15 16:32
@davisgiles I was having the same problem right now. I had the application in my Downloads folder. I moved Pocket Sync to the Applications folder in the Mac and now it works perfectly.

**Comment by arnauos** [comment] 2024-01-07 20:45
Hi, this just happened to me with 4.2.1 and Sonoma 14.2.1. Restarting the app makes it work sometimes but not always so something funky is happening.

video: https://we.tl/t-wLTqMprmsJ

**Comment by futurepr0n** [comment] 2024-01-11 14:53
I’m also struggling with getting the app to work on Mac. I insert my Microsd card to my card reader and select it as my pocket to sync. I see my games and memories etc all loaded, including installed cores but if I select any core to install the button doesn’t end up working.

I checked security and privacy settings and doesn’t seem to be any special permissions it’s asking for.

I installed it to applications from the dmg which apple did not like and did not have trust for the app, but I selected open anyway and got as much as the initial gui to work and read the sd card, it just doesn’t write. I can created new folders and copy files to the card fine as expected in regular finder.

**Comment by neil-morrison44** [comment] 2024-01-11 19:07
@futurepr0n what version of MacOS? What’s your SD Card’s name (that appears in Finder etc)?

**Comment by davisgiles** [comment] 2024-01-20 20:31
@neil-morrison44 I am having this issue again with the most recent updates to pocket sync. I am on a Macbook Pro M2 max, running Sonoma 14.2.1. The entire app works great, such as updating the pocket firmware but only the install/update of cores has not been functional lately. When I manually add the core to my SD card and relaunch pocket-sync it shows the core but I cannot install/update/remove cores inside the app.

**Comment by EvilPixelsKill** [comment] 2024-01-21 17:49
I have also experienced this issue at the weekend. I had to quit the app and it would eventually work. 

MacBook Pro M1

**Comment by futurepr0n** [comment] 2024-01-21 18:17
@neil-morrison44 hey sorry I was late to get back to this, I will edit this comment or add the specifics later but I am on Mac OSX 12 at the moment. I was able to eventually have success, I’m not sure why - you may want to double check in security and privacy and see if there’s any settings like file access that you haven’t enabled for pocket sync yet. You will also probably need to close the app, reboot, retry a couple times. I don’t know why but like others this was able to solve my issue. 

My SD card name is “POCKET” - you have fat32 or exfat? I  have fat32 formatted card at the moment and will need to reformat to exfat I think for some of the core or rom compatibility. Perhaps it’s an issue with being able to read but not write to the partition on your card?

**Comment by neil-morrison44** [comment] 2024-01-23 13:30
In v4.3.0 it'll now keep the log, so hopefully whatever's happening is output there.
If anyone runs into it again the log folder can be opened by going into settings and clicking the `Open Log Folder` down the bottom.

_Hopefully_ there'll be something in there that helps work out what's going on

**Comment by arnauos** [comment] 2024-01-23 20:34
Ok, so I did try to install a new core and on first try the install button did not work. I did several restarts of the app and it was then working each time but I was able to make it stop working again several times. Here are the logs, when it is not working, clicking the install button seems to log nothing 🤔

[Pocket SyncKO1.log](https://github.com/neil-morrison44/pocket-sync/files/14029528/Pocket.SyncKO1.log)
[Pocket SyncKO2.log](https://github.com/neil-morrison44/pocket-sync/files/14029529/Pocket.SyncKO2.log)
[Pocket SyncOK.log](https://github.com/neil-morrison44/pocket-sync/files/14029530/Pocket.SyncOK.log)

**Comment by colemichaelwenger** [comment] 2024-01-23 22:05
I'm not positive what exactly the call is or if it's important, but there
is a line in the log that looks suspiciously like a credential. Might want
to double check that.

**Comment by neil-morrison44** [comment] 2024-01-23 22:49
@colemichaelwenger yeah, I noticed that too - it's nothing to be concerned about though, just the URL Github redirects the (public API) request to which includes some expiry AWS params. 

So not my cred (Githubs) & public anyway since the app doesn't log into Github (or AWS)

**Comment by neil-morrison44** [comment] 2024-01-23 22:59
@arnauos thanks for the logs! As you say - doesn't seem to be anything too helpful in them...

Can you remember which times correlate to when you attempted to install a core & it did nothing?

---

My current thinking is that there's something which is becoming unreliable when the app is compiled for release, since I've still never seen it happen for any of my local debug builds... but it still doesn't make sense what exactly it is and why it'll switch between being fixed and broken - any why it stays broken until the app is restarted.

If I can get it happening locally on a "release" build I _might_ be able to slowly de-optimise the release settings until it goes away...

**Comment by arnauos** [comment] 2024-01-23 23:18
Once I got to the core section and selected a core and pressed the non working install nothing was added to the log, so both ko logs end just before i did try the install.

I restarted the app around 15 times, the install was not working on 3 out of 15 attempts.

**Comment by neil-morrison44** [comment] 2024-01-24 01:53
Has anyone ever seen the app go from working to non-working within one session of it being opened?

or does it sometimes just start up _bad_ and stays bad until restarted?

**Comment by neil-morrison44** [comment] 2024-01-29 00:23
That's v4.3.1 out now, it's got even more error logging in it so should - hopefully - point to what's going wrong.

If it was a weird timing thing then it might be fixed, but that seems unlikely.

**Comment by futurepr0n** [comment] 2024-02-07 17:10
> Has anyone ever seen the app go from working to non-working within one session of it being opened?
> 
> or does it sometimes just start up _bad_ and stays bad until restarted?

I had a problem but was probably bc I used developer usb mount instead of taking the sd card out. That could have been coincidental

**Comment by neil-morrison44** [comment] 2024-11-24 00:13
Closing this off since no one's reported it in a while, after lots of people reporting it at once.
v5 should have changed most things which could cause this, if it wasn't fixed earlier.

**Closed by neil-morrison44** 2024-11-24 00:13 UTC
Labels: bug
